### ISSUE TITLE
Review/update versions for UDN-Aus

### ISSUE THREAD

**Issue by ammazzaw** [Australian-Genomics/CTRL#125]
Review versions of dependencies for security. Update where possible without disrupting the current codebase.

This is a first step towards upgrading the whole CTRL ecosystem. Document all issues and solve the straightforward ones for UDN-Aus.

**Comment by DoxasticFox** [comment]
Related: #61 (which talks about updating dependencies).

Shazia noted that she encountered an issue to do with the docker version. I should have clarified, but I think she's probably referring to the version in the docker-compose.yml file.

**Comment by ammazzaw** [comment]
Closing as this issue is covered by #154 (and UDN-Aus has been delivered).
