### ISSUE TITLE
Ensure `db/seeds.rb` makes the`testuser@email.com` account

### ISSUE THREAD

**Issue by DoxasticFox** [Australian-Genomics/CTRL#29]
@mathob reports that `db/seeds.rb` is currently failing. It might be that the [call](https://github.com/Australian-Genomics/CTRL/blob/a6194f7a571d8925636aa740f4757fce285ed65e/db/seeds.rb#L12) to `User.create` is failing silently. IIRC, `User.create!` is the form which raises an exception. If so, all the `.create` calls in `db/seeds.rb` should be changed to `.create!` calls as part of this ticket.

**Comment by mathob** [comment]
The test user is created with study_id: 'A1543457', but if this study is not in the study_codes table then User.create fails. 
Adding a row in the database like this enables user creation to succeed:
`insert into study_codes(title,created_at,updated_at) values ('A1543457',now(),now());`

**Comment by DoxasticFox** [comment]
Resolved by https://github.com/Australian-Genomics/CTRL/pull/36.
