### ISSUE TITLE
The multiple choice buttons move when they are selected, when the page is returned to they appear normal. 

### ISSUE THREAD

**Issue by rosiejbrown** [Australian-Genomics/CTRL#45]
https://user-images.githubusercontent.com/110963329/186546754-c935cfcd-d07d-4cb2-b1c5-c83570e73a6c.mov

**Comment by DoxasticFox** [comment]
I'm closing this issue as I haven't been able to reproduce it and it doesn't seem to happen reliably. We can investigate again if it reemerges.
