### ISSUE TITLE
Responses on the final page aren't saving.

### ISSUE THREAD

**Issue by rosiejbrown** [Australian-Genomics/CTRL#46]
https://user-images.githubusercontent.com/110963329/186547581-8712e831-f717-42d3-b5e5-992d89c2d1a4.mov

Second half of video shows the responses saving on one page but not the last page.

**Comment by DoxasticFox** [comment]
The behaviour of the last page is actually the same as all the pages: Responses are saved when you click the "Next" button, but not when you click the "Back" button. I'll wire-up the "Back" button to save responses too.
